# mandatory (if you want to use the same wallpaper for more than one monitor, one preload is enough)
preload = /home/albert/Desktop/dotfiles/wallpapers/firegreen.jpg
preload = /home/albert/Desktop/dotfiles/wallpapers/fireblue.png


# comment or uncomment the wallpaper lines for its use
# settings for laptop
#wallpaper {
#       monitor = eDP-1
#       path = /home/albert/Desktop/dotfiles/wallpapers/firegreen.jpg
#}

# settings for dual monitor
#wallpaper {
#        monitor = HDMI-A-1
#        path = /home/albert/Desktop/dotfiles/wallpapers/firegreen.jpg
#}

#wallpaper {
#        monitor = DP-1
#        path = /home/albert/Desktop/dotfiles/wallpapers/fireblue.png
#}

# disable wallpaper comments
splash = false
